export const markets = [
  // MACRO REGIONS (UN STANDARD)
  { name: 'Global / Worldwide', code: 'GLB', type: 'region', context: 'international' },
  { name: 'Northern Africa', code: 'NAF', type: 'region', context: 'Northern African markets' },
  { name: 'Western Africa', code: 'WAF', type: 'region', context: 'Western African markets' },
  { name: 'Central Africa', code: 'CAF', type: 'region', context: 'Central African markets' },
  { name: 'Eastern Africa', code: 'EAF', type: 'region', context: 'Eastern African markets' },
  { name: 'Southern Africa', code: 'SAF', type: 'region', context: 'Southern African markets' },
  { name: 'Northern America', code: 'NAM', type: 'region', context: 'US, Canada, and Northern American regions' },
  { name: 'Central America', code: 'CAM', type: 'region', context: 'Central American markets' },
  { name: 'Caribbean', code: 'CRB', type: 'region', context: 'Caribbean island markets' },
  { name: 'South America', code: 'SAM', type: 'region', context: 'South American markets' },
  { name: 'Western Asia', code: 'WAS', type: 'region', context: 'Western Asian markets' },
  { name: 'Central Asia', code: 'CAS', type: 'region', context: 'Central Asian markets' },
  { name: 'South Asia', code: 'SAS', type: 'region', context: 'South Asian markets including India, Pakistan, etc.' },
  { name: 'Southeast Asia', code: 'SEA', type: 'region', context: 'Southeast Asian markets (ASEAN)' },
  { name: 'East Asia', code: 'EAS', type: 'region', context: 'East Asian markets (China, Japan, Korea)' },
  { name: 'Northern Europe', code: 'NEU', type: 'region', context: 'Northern European markets' },
  { name: 'Western Europe', code: 'WEU', type: 'region', context: 'Western European markets' },
  { name: 'Eastern Europe', code: 'EEU', type: 'region', context: 'Eastern European markets' },
  { name: 'Southern Europe', code: 'SEU', type: 'region', context: 'Southern European markets' },
  { name: 'Australia and New Zealand', code: 'ANZ', type: 'region', context: 'Oceania (AU/NZ) markets' },
  { name: 'Melanesia', code: 'MEL', type: 'region', context: 'Melanesian regions' },
  { name: 'Micronesia', code: 'MIC', type: 'region', context: 'Micronesian regions' },
  { name: 'Polynesia', code: 'POL', type: 'region', context: 'Polynesian regions' },
  
  // COUNTRIES
  { name: 'Afghanistan', code: 'AF', type: 'country' },
  { name: 'Albania', code: 'AL', type: 'country' },
  { name: 'Algeria', code: 'DZ', type: 'country' },
  { name: 'Andorra', code: 'AD', type: 'country' },
  { name: 'Angola', code: 'AO', type: 'country' },
  { name: 'Antigua and Barbuda', code: 'AG', type: 'country' },
  { name: 'Argentina', code: 'AR', type: 'country' },
  { name: 'Armenia', code: 'AM', type: 'country' },
  { name: 'Australia', code: 'AU', type: 'country' },
  { name: 'Austria', code: 'AT', type: 'country' },
  { name: 'Azerbaijan', code: 'AZ', type: 'country' },
  { name: 'Bahamas', code: 'BS', type: 'country' },
  { name: 'Bahrain', code: 'BH', type: 'country' },
  { name: 'Bangladesh', code: 'BD', type: 'country' },
  { name: 'Barbados', code: 'BB', type: 'country' },
  { name: 'Belarus', code: 'BY', type: 'country' },
  { name: 'Belgium', code: 'BE', type: 'country' },
  { name: 'Belize', code: 'BZ', type: 'country' },
  { name: 'Benin', code: 'BJ', type: 'country' },
  { name: 'Bhutan', code: 'BT', type: 'country' },
  { name: 'Bolivia', code: 'BO', type: 'country' },
  { name: 'Bosnia and Herzegovina', code: 'BA', type: 'country' },
  { name: 'Botswana', code: 'BW', type: 'country' },
  { name: 'Brazil', code: 'BR', type: 'country' },
  { name: 'Brunei Darussalam', code: 'BN', type: 'country' },
  { name: 'Bulgaria', code: 'BG', type: 'country' },
  { name: 'Burkina Faso', code: 'BF', type: 'country' },
  { name: 'Burundi', code: 'BI', type: 'country' },
  { name: 'Cabo Verde', code: 'CV', type: 'country' },
  { name: 'Cambodia', code: 'KH', type: 'country' },
  { name: 'Cameroon', code: 'CM', type: 'country' },
  { name: 'Canada', code: 'CA', type: 'country' },
  { name: 'Central African Republic', code: 'CF', type: 'country' },
  { name: 'Chad', code: 'TD', type: 'country' },
  { name: 'Chile', code: 'CL', type: 'country' },
  { name: 'China', code: 'CN', type: 'country' },
  { name: 'Colombia', code: 'CO', type: 'country' },
  { name: 'Comoros', code: 'KM', type: 'country' },
  { name: 'Congo', code: 'CG', type: 'country' },
  { name: 'Congo (Democratic Republic)', code: 'CD', type: 'country' },
  { name: 'Costa Rica', code: 'CR', type: 'country' },
  { name: 'Croatia', code: 'HR', type: 'country' },
  { name: 'Cuba', code: 'CU', type: 'country' },
  { name: 'Cyprus', code: 'CY', type: 'country' },
  { name: 'Czechia', code: 'CZ', type: 'country' },
  { name: 'Denmark', code: 'DK', type: 'country' },
  { name: 'Djibouti', code: 'DJ', type: 'country' },
  { name: 'Dominica', code: 'DM', type: 'country' },
  { name: 'Dominican Republic', code: 'DO', type: 'country' },
  { name: 'Ecuador', code: 'EC', type: 'country' },
  { name: 'Egypt', code: 'EG', type: 'country' },
  { name: 'El Salvador', code: 'SV', type: 'country' },
  { name: 'Equatorial Guinea', code: 'GQ', type: 'country' },
  { name: 'Eritrea', code: 'ER', type: 'country' },
  { name: 'Estonia', code: 'EE', type: 'country' },
  { name: 'Eswatini', code: 'SZ', type: 'country' },
  { name: 'Ethiopia', code: 'ET', type: 'country' },
  { name: 'Fiji', code: 'FJ', type: 'country' },
  { name: 'Finland', code: 'FI', type: 'country' },
  { name: 'France', code: 'FR', type: 'country' },
  { name: 'Gabon', code: 'GA', type: 'country' },
  { name: 'Gambia', code: 'GM', type: 'country' },
  { name: 'Georgia', code: 'GE', type: 'country' },
  { name: 'Germany', code: 'DE', type: 'country' },
  { name: 'Ghana', code: 'GH', type: 'country' },
  { name: 'Greece', code: 'GR', type: 'country' },
  { name: 'Grenada', code: 'GD', type: 'country' },
  { name: 'Guatemala', code: 'GT', type: 'country' },
  { name: 'Guinea', code: 'GN', type: 'country' },
  { name: 'Guinea-Bissau', code: 'GW', type: 'country' },
  { name: 'Guyana', code: 'GY', type: 'country' },
  { name: 'Haiti', code: 'HT', type: 'country' },
  { name: 'Honduras', code: 'HN', type: 'country' },
  { name: 'Hungary', code: 'HU', type: 'country' },
  { name: 'Iceland', code: 'IS', type: 'country' },
  { name: 'India', code: 'IN', type: 'country' },
  { name: 'Indonesia', code: 'ID', type: 'country' },
  { name: 'Iran', code: 'IR', type: 'country' },
  { name: 'Iraq', code: 'IQ', type: 'country' },
  { name: 'Ireland', code: 'IE', type: 'country' },
  { name: 'Israel', code: 'IL', type: 'country' },
  { name: 'Italy', code: 'IT', type: 'country' },
  { name: 'Jamaica', code: 'JM', type: 'country' },
  { name: 'Japan', code: 'JP', type: 'country' },
  { name: 'Jordan', code: 'JO', type: 'country' },
  { name: 'Kazakhstan', code: 'KZ', type: 'country' },
  { name: 'Kenya', code: 'KE', type: 'country' },
  { name: 'Kiribati', code: 'KI', type: 'country' },
  { name: 'Korea (North)', code: 'KP', type: 'country' },
  { name: 'Korea (South)', code: 'KR', type: 'country' },
  { name: 'Kuwait', code: 'KW', type: 'country' },
  { name: 'Kyrgyzstan', code: 'KG', type: 'country' },
  { name: 'Lao PDR', code: 'LA', type: 'country' },
  { name: 'Latvia', code: 'LV', type: 'country' },
  { name: 'Lebanon', code: 'LB', type: 'country' },
  { name: 'Lesotho', code: 'LS', type: 'country' },
  { name: 'Liberia', code: 'LR', type: 'country' },
  { name: 'Libya', code: 'LY', type: 'country' },
  { name: 'Liechtenstein', code: 'LI', type: 'country' },
  { name: 'Lithuania', code: 'LT', type: 'country' },
  { name: 'Luxembourg', code: 'LU', type: 'country' },
  { name: 'Madagascar', code: 'MG', type: 'country' },
  { name: 'Malawi', code: 'MW', type: 'country' },
  { name: 'Malaysia', code: 'MY', type: 'country' },
  { name: 'Maldives', code: 'MV', type: 'country' },
  { name: 'Mali', code: 'ML', type: 'country' },
  { name: 'Malta', code: 'MT', type: 'country' },
  { name: 'Marshall Islands', code: 'MH', type: 'country' },
  { name: 'Mauritania', code: 'MR', type: 'country' },
  { name: 'Mauritius', code: 'MU', type: 'country' },
  { name: 'Mexico', code: 'MX', type: 'country' },
  { name: 'Micronesia', code: 'FM', type: 'country' },
  { name: 'Moldova', code: 'MD', type: 'country' },
  { name: 'Monaco', code: 'MC', type: 'country' },
  { name: 'Mongolia', code: 'MN', type: 'country' },
  { name: 'Montenegro', code: 'ME', type: 'country' },
  { name: 'Morocco', code: 'MA', type: 'country' },
  { name: 'Mozambique', code: 'MZ', type: 'country' },
  { name: 'Myanmar', code: 'MM', type: 'country' },
  { name: 'Namibia', code: 'NA', type: 'country' },
  { name: 'Nauru', code: 'NR', type: 'country' },
  { name: 'Nepal', code: 'NP', type: 'country' },
  { name: 'Netherlands', code: 'NL', type: 'country' },
  { name: 'New Zealand', code: 'NZ', type: 'country' },
  { name: 'Nicaragua', code: 'NI', type: 'country' },
  { name: 'Niger', code: 'NE', type: 'country' },
  { name: 'Nigeria', code: 'NG', type: 'country' },
  { name: 'North Macedonia', code: 'MK', type: 'country' },
  { name: 'Norway', code: 'NO', type: 'country' },
  { name: 'Oman', code: 'OM', type: 'country' },
  { name: 'Pakistan', code: 'PK', type: 'country' },
  { name: 'Palau', code: 'PW', type: 'country' },
  { name: 'Panama', code: 'PA', type: 'country' },
  { name: 'Papua New Guinea', code: 'PG', type: 'country' },
  { name: 'Paraguay', code: 'PY', type: 'country' },
  { name: 'Peru', code: 'PE', type: 'country' },
  { name: 'Philippines', code: 'PH', type: 'country' },
  { name: 'Poland', code: 'PL', type: 'country' },
  { name: 'Portugal', code: 'PT', type: 'country' },
  { name: 'Qatar', code: 'QA', type: 'country' },
  { name: 'Romania', code: 'RO', type: 'country' },
  { name: 'Russian Federation', code: 'RU', type: 'country' },
  { name: 'Rwanda', code: 'RW', type: 'country' },
  { name: 'Saint Kitts and Nevis', code: 'KN', type: 'country' },
  { name: 'Saint Lucia', code: 'LC', type: 'country' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', type: 'country' },
  { name: 'Samoa', code: 'WS', type: 'country' },
  { name: 'San Marino', code: 'SM', type: 'country' },
  { name: 'Sao Tome and Principe', code: 'ST', type: 'country' },
  { name: 'Saudi Arabia', code: 'SA', type: 'country' },
  { name: 'Senegal', code: 'SN', type: 'country' },
  { name: 'Serbia', code: 'RS', type: 'country' },
  { name: 'Seychelles', code: 'SC', type: 'country' },
  { name: 'Sierra Leone', code: 'SL', type: 'country' },
  { name: 'Singapore', code: 'SG', type: 'country' },
  { name: 'Slovakia', code: 'SK', type: 'country' },
  { name: 'Slovenia', code: 'SI', type: 'country' },
  { name: 'Solomon Islands', code: 'SB', type: 'country' },
  { name: 'Somalia', code: 'SO', type: 'country' },
  { name: 'South Africa', code: 'ZA', type: 'country' },
  { name: 'South Sudan', code: 'SS', type: 'country' },
  { name: 'Spain', code: 'ES', type: 'country' },
  { name: 'Sri Lanka', code: 'LK', type: 'country' },
  { name: 'Sudan', code: 'SD', type: 'country' },
  { name: 'Suriname', code: 'SR', type: 'country' },
  { name: 'Sweden', code: 'SE', type: 'country' },
  { name: 'Switzerland', code: 'CH', type: 'country' },
  { name: 'Syrain Arab Republic', code: 'SY', type: 'country' },
  { name: 'Taiwan', code: 'TW', type: 'country' },
  { name: 'Tajikistan', code: 'TJ', type: 'country' },
  { name: 'Tanzania', code: 'TZ', type: 'country' },
  { name: 'Thailand', code: 'TH', type: 'country' },
  { name: 'Timor-Leste', code: 'TL', type: 'country' },
  { name: 'Togo', code: 'TG', type: 'country' },
  { name: 'Tonga', code: 'TO', type: 'country' },
  { name: 'Trinidad and Tobago', code: 'TT', type: 'country' },
  { name: 'Tunisia', code: 'TN', type: 'country' },
  { name: 'Turkey', code: 'TR', type: 'country' },
  { name: 'Turkmenistan', code: 'TM', type: 'country' },
  { name: 'Tuvalu', code: 'TV', type: 'country' },
  { name: 'Uganda', code: 'UG', type: 'country' },
  { name: 'Ukraine', code: 'UA', type: 'country' },
  { name: 'United Arab Emirates', code: 'AE', type: 'country' },
  { name: 'United Kingdom', code: 'GB', type: 'country' },
  { name: 'United States', code: 'US', type: 'country' },
  { name: 'Uruguay', code: 'UY', type: 'country' },
  { name: 'Uzbekistan', code: 'UZ', type: 'country' },
  { name: 'Vanuatu', code: 'VU', type: 'country' },
  { name: 'Venezuela', code: 'VE', type: 'country' },
  { name: 'Viet Nam', code: 'VN', type: 'country' },
  { name: 'Yemen', code: 'YE', type: 'country' },
  { name: 'Zambia', code: 'ZM', type: 'country' },
  { name: 'Zimbabwe', code: 'ZW', type: 'country' }
];
